/*
 * This file was automatically generated by EvoSuite
 * Fri May 27 12:18:25 GMT 2022
 */

package cs304.coveragelab;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import cs304.coveragelab.MessageBuilder;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MessageBuilder_ESTest extends MessageBuilder_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MessageBuilder messageBuilder0 = new MessageBuilder();
      String string0 = messageBuilder0.getMessage("qk|C");
      assertEquals("Hello qk|C", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MessageBuilder messageBuilder0 = new MessageBuilder();
      String string0 = messageBuilder0.getMessage("a");
      assertEquals("Hello a", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MessageBuilder messageBuilder0 = new MessageBuilder();
      String string0 = messageBuilder0.getMessage("Please provide a name!");
      assertEquals("Too long: Please provide a name!", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      MessageBuilder messageBuilder0 = new MessageBuilder();
      String string0 = messageBuilder0.getMessage("");
      assertEquals("Please provide a name!", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      MessageBuilder messageBuilder0 = new MessageBuilder();
      // Undeclared exception!
      try { 
        messageBuilder0.getMessage((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }
}
